package model.pojo;
// Generated 11-nov-2018 12:53:19 by Hibernate Tools 4.3.1



/**
 * Intercambio generated by hbm2java
 */
public class Intercambio  implements java.io.Serializable {


     private Integer idIntercambio;
     private int idAdmin;
     private String name;
     private String tipo;
     private String costo;
     private String dateA;
     private String date;
     private String comentarios;
     private String clave;

    public Intercambio() {
    }

    public Intercambio(int idAdmin, String name, String tipo, String costo, String dateA, String date, String comentarios, String clave) {
       this.idAdmin = idAdmin;
       this.name = name;
       this.tipo = tipo;
       this.costo = costo;
       this.dateA = dateA;
       this.date = date;
       this.comentarios = comentarios;
       this.clave = clave;
    }
   
    public Integer getIdIntercambio() {
        return this.idIntercambio;
    }
    
    public void setIdIntercambio(Integer idIntercambio) {
        this.idIntercambio = idIntercambio;
    }
    public int getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(int idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getCosto() {
        return this.costo;
    }
    
    public void setCosto(String costo) {
        this.costo = costo;
    }
    public String getDateA() {
        return this.dateA;
    }
    
    public void setDateA(String dateA) {
        this.dateA = dateA;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


