package model.pojo;
// Generated 11-nov-2018 12:53:19 by Hibernate Tools 4.3.1



/**
 * IntercambioMix generated by hbm2java
 */
public class IntercambioMix  implements java.io.Serializable {


     private Integer id;
     private int idIntercambio;
     private String random;

    public IntercambioMix() {
    }

    public IntercambioMix(int idIntercambio, String random) {
       this.idIntercambio = idIntercambio;
       this.random = random;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdIntercambio() {
        return this.idIntercambio;
    }
    
    public void setIdIntercambio(int idIntercambio) {
        this.idIntercambio = idIntercambio;
    }
    public String getRandom() {
        return this.random;
    }
    
    public void setRandom(String random) {
        this.random = random;
    }




}


